plante-app-team/plante

lib/ui/shop/shop_product_range_page.dart, test/model/country_test.dart, test/model/viewed_products_storage_test.dart, test/outside/off/off_shops_manager_test.dart, test/ui/base/components/shop_card_test.dart, test/ui/shop/shop_product_range_page_test.dart, test/ui/shop/shop_product_range_page_test_commons.dart
https://plante.atlassian.net/browse/PLANTEDEV-513
=> Don't show suggested products which are already in the shop

lib/base/base.dart, lib/base/file_system_utils.dart, lib/di.dart, lib/logging/log.dart, lib/model/country.g.dart, lib/outside/backend/backend.dart, lib/outside/map/osm_overpass.dart, lib/outside/off/fake_off_api.dart, lib/outside/off/off_api.dart, lib/outside/off/off_shops_list_obtainer.dart, lib/outside/off/off_shops_manager.dart, test/base/file_system_utils_test.dart, test/common_mocks.mocks.dart, test/outside/off/off_api_test.dart, test/outside/off/off_shops_list_obtainer_test.dart, test/outside/off/off_shops_manager_test.dart, test/z_fakes/fake_off_shops_list_obtainer.dart, test/z_fakes/fake_off_shops_manager.dart
https://github.com/plante-app-team/plante/issues/20
=> Store OFF shops JSON persistently

lib/di.dart, lib/outside/off/off_cacher.dart, lib/outside/off/off_shop.dart, lib/outside/off/off_shop.g.dart, lib/outside/off/off_shops_manager.dart, lib/outside/off/off_vegan_barcodes_obtainer.dart, lib/outside/off/off_vegan_barcodes_storage.dart, lib/outside/products/suggested_products_manager.dart, test/common_mocks.mocks.dart, test/outside/off/off_api_test.dart, test/outside/off/off_cacher_test.dart, test/outside/off/off_shops_list_wrapper_test.dart, test/outside/off/off_shops_manager_test.dart, test/outside/off/off_vegan_barcodes_obtainer_test.dart, test/outside/off/off_vegan_barcodes_storage_test.dart, test/outside/products/suggested_products_manager_test.dart, test/ui/shop/shop_product_range_page_suggested_products_test.dart, test/ui/shop/shop_product_range_page_test_commons.dart, test/z_fakes/fake_off_shops_manager.dart, test/z_fakes/fake_off_vegan_barcodes_obtainer.dart
https://github.com/plante-app-team/plante/issues/20
=> Cache barcodes of OFF shops

lib/di.dart, lib/model/lang_code.dart, lib/outside/map/extra_properties/barcode_property.dart, lib/outside/map/extra_properties/map_extra_properties_cacher.dart, lib/outside/map/extra_properties/product_at_shop_extra_property.dart, lib/outside/map/extra_properties/product_at_shop_extra_property.g.dart, lib/outside/map/extra_properties/product_at_shop_extra_property_type.dart, lib/outside/map/extra_properties/products_at_shops_extra_properties_manager.dart, lib/outside/map/osm/osm_uid.dart, lib/outside/products/suggested_products_manager.dart, lib/ui/shop/_confirmed_products_model.dart, lib/ui/shop/_suggested_products_model.dart, lib/ui/shop/shop_product_range_page.dart, lib/ui/shop/shop_product_range_page_model.dart, test/outside/map/extra_properties/map_extra_properties_cacher_test.dart, test/outside/map/extra_properties/product_at_shop_extra_property_type_test.dart, test/outside/map/extra_properties/products_at_shops_extra_properties_manager_test.dart, test/outside/products/suggested_products_manager_test.dart, test/ui/base/components/shop_card_test.dart, test/ui/shop/shop_product_range_page_suggested_products_test.dart, test/ui/shop/shop_product_range_page_test_commons.dart, test/z_fakes/fake_map_extra_properties_cacher.dart, test/z_fakes/fake_products_at_shops_extra_properties_manager.dart
https://github.com/plante-app-team/plante/issues/30
=> Add user-shop interactions persistent storage

lib/ui/shop/_suggested_products_model.dart, lib/ui/shop/shop_product_range_page_model.dart, test/ui/shop/shop_product_range_page_suggested_products_test.dart, test/z_fakes/fake_shops_manager.dart
https://github.com/plante-app-team/plante/issues/33
=> Support adding of suggested products to shops

lib/base/base.dart, lib/outside/off/fake_off_api.dart, lib/outside/off/off_api.dart, lib/outside/off/off_shops_manager.dart, lib/outside/off/off_vegan_barcodes_obtainer.dart, lib/outside/products/suggested_products_manager.dart, lib/ui/map/map_page/map_page_model.dart, lib/ui/shop/_suggested_products_model.dart, test/common_mocks.mocks.dart, test/outside/off/off_api_test.dart, test/outside/off/off_shops_manager_test.dart, test/outside/off/off_vegan_barcodes_obtainer_test.dart, test/outside/products/suggested_products_manager_test.dart, test/z_fakes/fake_off_shops_manager.dart, test/z_fakes/fake_off_vegan_barcodes_obtainer.dart, test/z_fakes/fake_suggested_products_manager.dart
https://plante.atlassian.net/browse/PLANTEDEV-518
=> Load shops with suggestions gradually, cancelling old loading when map is scrolled

lib/ui/shop/shop_product_range_page.dart, test/ui/shop/shop_product_range_page_suggested_products_test.dart, test/ui/shop/shop_product_range_page_test_commons.dart
https://plante.atlassian.net/browse/PLANTEDEV-558
=> Don't show "Last seen" date on suggested products

lib/outside/off/off_api.dart, lib/outside/off/off_vegan_barcodes_obtainer.dart, test/outside/off/off_api_test.dart
https://plante.atlassian.net/browse/PLANTEDEV-515
=> Order OFF suggestions by their creation date (newest first)

lib/l10n/app_en.arb, lib/ui/base/components/product_card.dart, lib/ui/shop/shop_product_range_page.dart, lib/ui/shop/shop_product_range_products_title.dart, test/ui/shop/shop_product_range_page_suggested_products_test.dart
In ShopProductsRangePage:
- Add a title for confirmed products
- Change suggested products title
- Add a distinct hint to each suggested product
=> Changes in ShopProductsRangePage

lib/ui/base/ui_value_wrapper.dart, lib/ui/map/map_page/map_page.dart, lib/ui/map/map_page/map_page_mode.dart, lib/ui/map/map_page/map_page_mode_default.dart, lib/ui/map/map_page/map_page_mode_zoomed_out.dart, lib/ui/map/map_page/map_page_model.dart, test/ui/map/map_page/map_page_model_test.dart, test/ui/map/map_page/map_page_suggested_products_test.dart
https://plante.atlassian.net/browse/PLANTEDEV-564
=> Stop loading suggested products when map is zoomed out

lib/l10n/app_en.arb, lib/ui/base/components/shop_card.dart, test/ui/base/components/shop_card_test.dart, test/ui/map/map_page/map_page_suggested_products_test.dart
https://github.com/plante-app-team/plante/issues/68
=> On ShopCard display same label "products listed" for shops with suggestions only

lib/outside/map/shops_large_local_cache_wrapper.dart, lib/outside/map/shops_manager.dart, lib/outside/products/suggestions/_radius_products_suggestions_manager.dart, lib/outside/products/suggestions/suggested_products_manager.dart, test/common_mocks.mocks.dart, test/outside/map/shops_large_local_cache_wrapper_test.dart, test/outside/map/shops_manager_clear_cache_test.dart, test/outside/map/shops_manager_create_shop_test.dart, test/outside/map/shops_manager_fetch_shop_product_range_test.dart, test/outside/map/shops_manager_fetch_shops_test.dart, test/outside/map/shops_manager_inflate_osm_shops_test.dart, test/outside/map/shops_manager_product_presence_vote_test.dart, test/outside/map/shops_manager_put_product_to_shop_test.dart, test/outside/map/shops_manager_test_commons.dart, test/outside/products/suggestions/_radius_products_suggestions_manager_test.dart, test/outside/products/suggestions/suggested_products_manager_test.dart, test/z_fakes/fake_shops_manager.dart
https://github.com/plante-app-team/plante/issues/70
=> Suggested products optimization #1

lib/ui/map/components/delayed_loading_notifier.dart, lib/ui/map/components/delayed_lossy_arg_callback.dart, lib/ui/map/map_page/map_page.dart, lib/ui/map/map_page/map_page_model.dart, lib/ui/map/map_page/markers_builder.dart, test/ui/map/components/delayed_loading_notifier_test.dart, test/ui/map/components/delayed_lossy_arg_callback_test.dart
https://github.com/plante-app-team/plante/issues/70
=> Multiple map optimizations

README.md, lib/outside/off/off_geo_helper.dart, lib/outside/off/off_vegan_barcodes_obtainer.dart, test/outside/off/off_geo_helper_test.dart
https://github.com/plante-app-team/plante/issues/63
=> Add the OFF Plant-based-foods category to products when they are being put to the map

lib/l10n/app_en.arb, lib/outside/backend/backend.dart, lib/outside/backend/user_avatar_manager.dart, lib/ui/base/colors_plante.dart, lib/ui/base/components/veg_status_displayed.dart, lib/ui/base/text_styles.dart, lib/ui/first_screen/init_user_page.dart, lib/ui/profile/avatar_widget.dart, lib/ui/profile/edit_user_data_widget.dart, test/common_mocks.mocks.dart, test/outside/backend/backend_test.dart, test/outside/backend/user_avatar_manager_test.dart, test/ui/first_screen/init_user_page_test.dart, test/ui/profile/edit_user_data_widget_test.dart, test/z_fakes/fake_user_avatar_manager.dart, test/z_fakes/fake_user_langs_manager.dart
https://github.com/plante-app-team/plante/issues/99
https://github.com/plante-app-team/plante/issues/120
=> Apply proper design to EditUserDataWidget and support avatar deletion

lib/l10n/app_en.arb, lib/outside/backend/user_avatar_manager.dart, lib/ui/crop/image_crop_page.dart, lib/ui/photos_taker.dart, test/common_mocks.mocks.dart, test/outside/backend/user_avatar_manager_test.dart
https://github.com/plante-app-team/plante/issues/123
=> Prohibit selection of too small avatar images

lib/ui/crop/image_crop_page.dart, lib/ui/product/init_product_page_model.dart, test/ui/product/init_product_page_test.dart
https://github.com/plante-app-team/plante/issues/5
=> Ensure cropped product image is not smaller than min size

lib/ui/scan/barcode_scan_page.dart, lib/ui/scan/barcode_scan_page_model.dart, test/ui/base/components/shop_card_test.dart, test/ui/scan/barcode_scan_page_test.dart
https://github.com/plante-app-team/plante/issues/100
=> Add to History all scanned products

lib/outside/backend/backend.dart, lib/outside/off/off_geo_helper.dart, test/outside/backend/backend_test.dart
https://github.com/plante-app-team/plante/issues/101
=> Set the new "edited" param when user creates a product

README.md, lib/l10n/app_en.arb, lib/model/user_params.dart, lib/model/user_params.g.dart, lib/model/user_params_controller.dart, lib/outside/backend/backend.dart, lib/ui/base/components/header_plante.dart, lib/ui/base/components/input_field_multiline_plante.dart, lib/ui/profile/avatar_widget.dart, lib/ui/profile/edit_profile_page.dart, lib/ui/profile/edit_user_data_widget.dart, lib/ui/profile/profile_page.dart, lib/ui/scan/barcode_scan_page.dart, lib/ui/settings/settings_page.dart, test/model/user_params_controller_test.dart, test/outside/backend/backend_test.dart, test/ui/first_screen/init_user_page_test.dart, test/ui/profile/edit_user_data_widget_test.dart, test/ui/profile/profile_page_test.dart, test/z_fakes/fake_user_avatar_manager.dart
https://github.com/plante-app-team/plante/issues/103
=> Implement header of the Profile page

lib/l10n/app_en.arb, lib/ui/base/components/input_field_multiline_plante.dart, lib/ui/base/text_styles.dart, lib/ui/base/ui_utils.dart, lib/ui/profile/edit_profile_page.dart, lib/ui/profile/edit_user_data_widget.dart, test/ui/profile/edit_profile_page_test.dart, test/ui/profile/profile_page_test.dart, test/z_fakes/fake_user_avatar_manager.dart
https://github.com/plante-app-team/plante/issues/104
=> Implement profile editing

lib/di.dart, lib/outside/backend/user_avatar_manager.dart, lib/ui/photos/photo_requester.dart, lib/ui/photos/photos_taker.dart, lib/ui/product/init_product_page.dart, lib/ui/product/init_product_page_model.dart, test/common_mocks.dart, test/common_mocks.mocks.dart, test/outside/backend/user_avatar_manager_test.dart, test/ui/main/main_page_test.dart, test/ui/photos/photo_requester_test.dart, test/ui/product/display_product_page_test.dart, test/ui/product/init_product_page_test.dart, test/ui/product/product_page_wrapper_test.dart, test/ui/scan/barcode_scan_page_test.dart, test/ui/shop/shop_product_range_page_test_commons.dart
https://github.com/plante-app-team/plante/issues/129
=> Ensure when adding a product the retrieved lost product photo is never user avatar

lib/base/general_error.dart, lib/contributions/user_contributions_manager.dart, lib/l10n/app_en.arb, lib/ui/base/components/invisible_widget.dart, lib/ui/profile/components/contributed_by_user_products_widget.dart, lib/ui/profile/components/products_history_widget.dart, lib/ui/profile/profile_page.dart, test/ui/main/main_page_test.dart, test/ui/profile/components/contributed_by_user_products_widget_test.dart, test/ui/profile/profile_page_products_lists_test.dart, test/ui/profile/profile_page_test_commons.dart, test/z_fakes/fake_user_contributions_manager.dart
https://github.com/plante-app-team/plante/issues/106
=> Add a list of products the user has contributed to the app

lib/ui/first_screen/init_user_page.dart
https://github.com/plante-app-team/plante/issues/131
=> Fix the top progress bar being no longer visible in InitUserPage

lib/ui/map/map_page/map_page.dart
https://github.com/plante-app-team/plante/issues/111
=> Fix: Map progress bar forces other UI elements to move

lib/ui/base/components/header_plante.dart, lib/ui/map/map_page/map_page.dart, lib/ui/profile/edit_profile_page.dart, lib/ui/profile/profile_page.dart
https://github.com/plante-app-team/plante/issues/146
=> Move down top controls on every screen

assets/copy.svg, lib/l10n/app_en.arb, lib/ui/base/components/checkbox_plante.dart, lib/ui/langs/user_langs_page.dart, lib/ui/settings/settings_buttons.dart, lib/ui/settings/settings_cache_page.dart, lib/ui/settings/settings_page.dart, pubspec.yaml
https://github.com/plante-app-team/plante/issues/108
=> Apply new Settings design

lib/ui/map/map_page/map_page_mode_create_shop.dart
https://github.com/plante-app-team/plante/issues/119
=> Cancel map's shop creation mode on back press

lib/outside/backend/user_avatar_manager.dart, lib/ui/crop/image_crop_page.dart, lib/ui/photos/photos_taker.dart, lib/ui/product/init_product_page_model.dart, test/common_mocks.mocks.dart, test/outside/backend/user_avatar_manager_test.dart, test/ui/product/init_product_page_test.dart
https://github.com/plante-app-team/plante/issues/114
=> Properly compress images before sending them to Open Food Facts

lib/l10n/app_de.arb, lib/l10n/app_el.arb, lib/l10n/app_nl.arb, lib/l10n/app_pl.arb, lib/l10n/app_ru.arb
https://github.com/plante-app-team/plante/issues/152
=> Pull fresh translations for the Profile release

lib/l10n/app_en.arb, lib/ui/map/map_page/map_page_timed_hints.dart
https://github.com/plante-app-team/plante/issues/174
=> Strings enhancements - fixes and contexts additions

lib/base/coord_utils.dart, lib/base/optional.dart, lib/base/settings.dart, lib/di.dart, lib/l10n/app_en.arb, lib/outside/map/displayed_distance_units_manager.dart, lib/ui/map/components/map_search_result_entry.dart, lib/ui/map/search_page/map_search_page.dart, lib/ui/map/search_page/map_search_page_model.dart, lib/ui/settings/settings_page.dart, test/base/settings_test.dart, test/outside/map/displayed_distance_units_manager_test.dart, test/ui/map/map_page/map_page_modes_test_commons.dart, test/ui/map/search_page/map_search_page_test.dart, test/ui/profile/profile_page_test_commons.dart, test/z_fakes/fake_settings.dart
https://github.com/plante-app-team/plante/issues/161
=> In countries where applicable use Feet and Miles instead of Meters and Kms

lib/ui/map/map_page/map_page_mode_default.dart, lib/ui/map/search_page/map_search_page.dart, test/ui/map/search_page/map_search_page_test.dart
- Fix found shops not being displayed until roads search is finished
- All-Filters-Selected bug fix attempt
=> Pre release fixes

lib/l10n/app_el.arb
https://github.com/plante-app-team/plante/issues/170
=> Fix a small issue with some Greek strings

lib/base/general_error.dart, lib/di.dart, lib/l10n/app_en.arb, lib/ui/base/page_state_plante.dart, lib/ui/map/map_page/map_page.dart, lib/ui/map/map_page/map_page_mode_create_shop.dart, lib/ui/map/map_page/map_page_mode_default.dart, lib/ui/map/map_page/map_page_model.dart, lib/ui/map/shop_creation/create_shop_page.dart, lib/ui/map/shop_creation/pick_existing_shop_page.dart, lib/ui/map/shop_creation/shops_creation_manager.dart, test/common_mocks.dart, test/common_mocks.mocks.dart, test/ui/main/main_page_test.dart, test/ui/map/map_page/map_page_mode_create_shop_test.dart, test/ui/map/map_page/map_page_model_test.dart, test/ui/map/map_page/map_page_modes_test_commons.dart, test/ui/map/shop_creation/create_shop_page_test.dart, test/ui/map/shop_creation/pick_existing_shop_page_test.dart, test/ui/map/shop_creation/shops_creation_manager_test.dart, test/ui/product/display_product_page_test.dart, test/ui/product/init_product_page_test.dart
https://github.com/plante-app-team/plante/issues/167
=> When user creates a new shop, suggest them to use one of the other shops nearby

lib/ui/base/components/incremental_progress_bar.dart
https://github.com/plante-app-team/plante/issues/164
=> Fix: Map progressbar often hangs

lib/ui/map/components/map_filter_check_button.dart, lib/ui/map/map_page/map_page.dart, lib/ui/map/map_page/map_page_mode_default.dart
https://github.com/plante-app-team/plante/issues/190
=> Fix padding below the map search bar

lib/l10n/app_en.arb, lib/ui/base/components/header_plante.dart, lib/ui/map/components/map_filter_check_button.dart, lib/ui/product/display_product_page.dart, lib/ui/product/product_barcode_dialog.dart, lib/ui/product/product_report_dialog.dart, test/ui/product/display_product_page_test.dart
https://github.com/plante-app-team/plante/issues/4
=> Add an ability to see and copy product barcode

lib/ui/product/init_product_page.dart, lib/ui/product/init_product_page_model.dart, test/ui/product/init_product_page_test.dart
https://github.com/plante-app-team/plante/issues/191
=> Add created-by-the-user products to the Recently Viewed products list

lib/ui/map/map_page/map_page_model.dart, test/ui/map/map_page/map_page_model_test.dart
https://github.com/plante-app-team/plante/issues/192
=> Fix: Bug: when a new territory is loaded, markers don't show up until the map is moved a bit

lib/ui/settings/settings_buttons.dart
https://github.com/plante-app-team/plante/issues/194
=> Apply proper design to checkmarks in Settings

lib/ui/map/shop_creation/create_shop_page.dart, test/ui/map/shop_creation/create_shop_page_test.dart
https://github.com/plante-app-team/plante/issues/224
=> Fix: CRITICAL BUG: shops duplication

assets/bottom_bar_news_feed.svg, lib/base/build_value_helper.dart, lib/base/build_value_helper.g.dart, lib/model/coord.dart, lib/outside/backend/backend.dart, lib/outside/backend/news/news_data_response.dart, lib/outside/backend/news/news_data_response.g.dart, lib/outside/backend/news/news_feed_manager.dart, lib/outside/backend/news/news_piece.dart, lib/outside/backend/news/news_piece.g.dart, lib/outside/backend/news/news_piece_product_at_shop.dart, lib/outside/backend/news/news_piece_product_at_shop.g.dart, lib/outside/backend/news/news_piece_type.dart, lib/ui/base/popup/popup_plante.dart, lib/ui/main/main_page.dart, lib/ui/news/news_feed_page.dart, pubspec.yaml, test/common_mocks.mocks.dart, test/model/coord_test.dart, test/outside/backend/backend_test.dart, test/outside/backend/news/news_feed_manager_test.dart, test/outside/backend/news/news_piece_test.dart, test/outside/backend/news/news_piece_type_test.dart, test/z_fakes/fake_http_client.dart
https://github.com/plante-app-team/plante/issues/226
=> Create NewsFeedManager, NewsPiece, blank NewsFeedPage and a few other things

lib/di.dart, lib/l10n/app_en.arb, lib/outside/backend/news/news_feed_manager.dart, lib/outside/map/osm/osm_territory_cacher.dart, lib/outside/map/roads_manager.dart, lib/outside/map/shops_manager.dart, lib/outside/map/shops_manager_shops_territories_fetcher.dart, lib/ui/base/text_styles.dart, lib/ui/news/news_feed_page.dart, lib/ui/news/news_feed_page_model.dart, lib/ui/product/display_product_page.dart, lib/ui/product/product_header_widget.dart, lib/ui/settings/settings_cache_page.dart, test/outside/map/osm/osm_territory_cacher_test.dart, test/outside/map/roads_manager_test.dart, test/outside/map/shops_manager_fetch_shops_by_uids.dart, test/outside/map/shops_manager_test_commons.dart, test/ui/main/main_page_test.dart, test/ui/map/map_page/map_page_mode_add_product_test.dart, test/ui/map/map_page/map_page_model_test.dart, test/ui/map/map_page/map_page_modes_test_commons.dart, test/ui/news/news_feed_page_test.dart, test/z_fakes/fake_news_feed_manager.dart, test/z_fakes/fake_osm_cacher.dart, test/z_fakes/fake_shops_manager.dart
https://github.com/plante-app-team/plante/issues/226
=> First implementation of News Feed UI

lib/ui/news/news_feed_page.dart, test/ui/main/main_page_test.dart
https://github.com/plante-app-team/plante/issues/237
=> Load news only when News Page is opened

lib/di.dart, lib/outside/news/news_feed_manager.dart, lib/ui/news/news_feed_page.dart, lib/ui/news/news_feed_page_model.dart, test/outside/news/news_feed_manager_test.dart, test/ui/main/main_page_test.dart, test/ui/news/news_feed_page_test.dart, test/z_fakes/fake_news_feed_manager.dart
https://github.com/plante-app-team/plante/issues/230
=> Re-request news on the news feed page opening when the map is moved far enough

lib/l10n/app_en.arb, lib/ui/base/components/appearing_circular_progress_indicator_plante.dart, lib/ui/product/display_product_page.dart, test/ui/product/display_product_page_test.dart
https://github.com/plante-app-team/plante/issues/243
=> Don't show the "Show where sold" button if the product is not sold nearby

lib/ui/product/display_product_page_model.dart, test/ui/product/display_product_page_test.dart, test/ui/scan/barcode_scan_page_test.dart
https://github.com/plante-app-team/plante/issues/244
=> In DisplayProductPage fetch the area around the map camera if necessary

lib/contributions/user_contribution_type.dart, lib/contributions/user_contributions_manager.dart, lib/l10n/app_en.arb, lib/logging/analytics.dart, lib/logging/underlying_analytics.dart, lib/logging/underlying_analytics_firebase.dart, lib/outside/backend/backend.dart, lib/outside/backend/user_report_data.dart, lib/outside/backend/user_reports_maker.dart, lib/ui/base/popup/popup_plante.dart, lib/ui/news/news_feed_page.dart, lib/ui/news/news_piece_product_at_shop_widget.dart, lib/ui/product/display_product_page_model.dart, lib/ui/report/report_dialog.dart, lib/ui/report/report_dialog_behaviour.dart, test/common_mocks.dart, test/common_mocks.mocks.dart, test/contributions/user_contribution_type_test.dart, test/contributions/user_contributions_manager_test.dart, test/logging/analytics_test.dart, test/logging/underlying_analytics_firebase_test.dart, test/outside/backend/backend_test.dart, test/outside/backend/user_reports_maker_test.dart, test/ui/news/news_feed_page_test.dart, test/ui/report/report_dialog_test.dart, test/z_fakes/fake_user_reports_maker.dart
https://github.com/plante-app-team/plante/issues/253
=> Add ability to report a news piece

lib/l10n/app_ro.arb, lib/l10n/app_ru.arb
[Poeditor Romanian](https://poeditor.com/projects/po_edit?id=490023&id_language=131&filter=&order=&per_page=20&page=1)
[Poeditor Russian](https://poeditor.com/projects/po_edit?id=490023&id_language=134&filter=&order=&per_page=20&page=1)
=> Add l10n RO, update l10n RU
